package com.mycompany.equipe43.Vue;



/**
 *
 * @author etudiant
 */
import com.mycompany.equipe43.Domaine.Controleur;
import com.mycompany.equipe43.Domaine.TypeMeubleSansDrain;
import com.mycompany.equipe43.Domaine.DTO.PieceDTO;
import java.awt.BorderLayout;
import com.mycompany.equipe43.Domaine.MeubleSansDrain;

import java.awt.FlowLayout;
import javax.swing.JFrame;

//import javax.swing.KeyStroke;
//import java.awt.event.KeyEvent;
//import java.awt.event.InputEvent;

public class MainWindow extends javax.swing.JFrame {

    private Controleur controleur;
    private DrawingPanel drawing;

public MainWindow() {
    
    initComponents();
    controleur = new Controleur();
    drawing = new DrawingPanel(controleur);
    drawing.setBackground(new java.awt.Color(51, 51, 51));
    oldDrawingPanel.setLayout(new BorderLayout());
    oldDrawingPanel.add(drawing, BorderLayout.CENTER);
    oldDrawingPanel.revalidate();
    oldDrawingPanel.repaint();
    drawing.setMainWindow(this);
    // Initialiser les champs avec les dimensions de la pièce par défaut
    PieceDTO pieceInitiale = controleur.getPiece();
    if (pieceInitiale != null) {
        // Remplir les champs de création de pièce
        largeur1.setText(String.valueOf(pieceInitiale.getLargeur()));
        longueur1.setText(String.valueOf(pieceInitiale.getLongueur()));
    }
    jMenuItem7.addActionListener(evt -> jMenuItem7ActionPerformed(evt));

// === Supprimer la sélection
/* javax.swing.JMenuItem supprimerSelection = new javax.swing.JMenuItem("Supprimer la sélection");
menuSupprimerElement.add(supprimerSelection);

supprimerSelection.addActionListener(evt1 -> {
    boolean suppressionOk = controleur.supprimerMeubleSelectionne();
    if (!suppressionOk) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aucun meuble sélectionné.",
            "Suppression",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    NomElementSelectionne.setText("** ??? **");
    longueur2.setText("");
    largeur2.setText("");
    oldDrawingPanel.repaint();
}); // <-- IMPORTANT : on ferme bien le listener ici

// === Redimensionner élément → Appliquer au sélectionné
//javax.swing.JMenuItem appliquerRedimension = new javax.swing.JMenuItem("Appliquer au sélectionné");
//jMenu4.add(appliquerRedimension);

appliquerRedimension.addActionListener(evt2 -> {
    try {
        int nouvelleLargeur = Integer.parseInt(largeur2.getText().trim());
        int nouvelleLongueur = Integer.parseInt(longueur2.getText().trim());

        boolean resizeOk = controleur.redimensionnerMeubleSelectionne(nouvelleLargeur, nouvelleLongueur);
        if (!resizeOk) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Aucun meuble sélectionné ou valeurs invalides.",
                "Redimensionnement",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        oldDrawingPanel.repaint();
        afficherMeubleSelectionne();

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Veuillez entrer des nombres valides pour largeur/longueur.",
            "Erreur",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
});

// });
    // });
*/
}



// Méthode publique pour mettre à jour les champs
    public void updateTailleFields() {
        PieceDTO piece = controleur.getPiece();
        if (piece != null) {
            largeur1.setText(String.valueOf(piece.getLargeur()));
            longueur1.setText(String.valueOf(piece.getLongueur()));
        }
        oldDrawingPanel.revalidate();
        oldDrawingPanel.repaint();
        this.revalidate();  // Rafraîchit toute la fenêtre
    }


    public void afficherMeubleSelectionne() {
    MeubleSansDrain meuble = controleur.getMeubleSelectionne();
    if (meuble != null) {
        String info = String.format("Meuble sélectionné: %s (Largeur: %d, Hauteur: %d)",
            meuble.getType(),
            meuble.getTaille().width,
            meuble.getTaille().height);
        largeur2.setText(String.valueOf(meuble.getTaille().width));   // largeur ← width
        longueur2.setText(String.valueOf(meuble.getTaille().height)); // longueur ← height
        AxeX.setText(String.valueOf(meuble.getPosition().x));
        AxeY.setText(String.valueOf(meuble.getPosition().y));
        // Afficher dans la console ou dans un label
        System.out.println(info);
    }
    oldDrawingPanel.revalidate();
    oldDrawingPanel.repaint();
    this.revalidate();  // Rafraîchit toute la fenêtre
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        ButtonTopPanel = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));
        ModeActive = new javax.swing.JLabel();
        ModeApp = new javax.swing.JComboBox<>();
        oldDrawingPanel = new javax.swing.JPanel();
        EditionPanel = new javax.swing.JPanel();
        editionTailleElementSelectionne = new javax.swing.JLabel();
        NomElementSelectionne = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        largeur1 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        largeurLabel1 = new javax.swing.JLabel();
        longueur1 = new javax.swing.JTextField();
        longueurLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        largeur2 = new javax.swing.JTextField();
        longueur2 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        longueurLabel2 = new javax.swing.JLabel();
        largeurLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AxeX = new javax.swing.JTextField();
        AxeY = new javax.swing.JTextField();
        jButtonDeplacer = new javax.swing.JButton();
        buttonSupprimerElement = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        SaveProjectMenu = new javax.swing.JMenu();
        saveProject = new javax.swing.JMenuItem();
        LoadProjectMenu = new javax.swing.JMenuItem();
        exportPNG = new javax.swing.JMenuItem();
        nouvellePiece = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        zoomIn = new javax.swing.JMenuItem();
        zoomOut = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoMenu = new javax.swing.JMenuItem();
        redoMenu = new javax.swing.JMenuItem();
        quitMenu = new javax.swing.JMenu();
        AjouterElementMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        ButtonTopPanel.setBackground(new java.awt.Color(102, 102, 102));
        ButtonTopPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ButtonTopPanel.setPreferredSize(new java.awt.Dimension(400, 35));

        ModeActive.setForeground(new java.awt.Color(255, 255, 255));
        ModeActive.setText("Mode  activé :");
        ButtonTopPanel.add(ModeActive);

        ModeApp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modélisation", "Edition" }));
        ModeApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeAppActionPerformed(evt);
            }
        });
        ButtonTopPanel.add(ModeApp);

        getContentPane().add(ButtonTopPanel, java.awt.BorderLayout.NORTH);

        oldDrawingPanel.setBackground(new java.awt.Color(51, 51, 51));

        EditionPanel.setBackground(new java.awt.Color(102, 102, 102));
        EditionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        editionTailleElementSelectionne.setForeground(new java.awt.Color(255, 255, 255));
        editionTailleElementSelectionne.setText("Element séléctionné :");

        NomElementSelectionne.setForeground(new java.awt.Color(255, 255, 255));
        NomElementSelectionne.setText("** ??? **");

        jButton3.setText("Redimensionner la pièce");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        largeur1.setText("500");
        largeur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeur1ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "inch", "px" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        largeurLabel1.setText("Longueur");

        longueur1.setText("500");
        longueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longueur1ActionPerformed(evt);
            }
        });

        longueurLabel1.setText("Largeur");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Type de Pièce");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "régulière", "irrégulière" }));

        jButton4.setText("Modifier taille");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        largeur2.setText("500");
        largeur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeur2ActionPerformed(evt);
            }
        });

        longueur2.setText("500");
        longueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longueur2ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "inch", "px" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        longueurLabel2.setText("Largeur");

        largeurLabel2.setText("Longueur");

        jButton5.setText("Créer la pièce");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Axe X");

        jLabel3.setText("Axe Y");

        AxeX.setText("0");
        AxeX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AxeXActionPerformed(evt);
            }
        });

        AxeY.setText("0");

        jButtonDeplacer.setText("Déplacer element");
        jButtonDeplacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeplacerActionPerformed(evt);
            }
        });

        buttonSupprimerElement.setText("Supprimer element");
        buttonSupprimerElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerElementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditionPanelLayout = new javax.swing.GroupLayout(EditionPanel);
        EditionPanel.setLayout(EditionPanelLayout);
        EditionPanelLayout.setHorizontalGroup(
            EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditionPanelLayout.createSequentialGroup()
                        .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditionPanelLayout.createSequentialGroup()
                                .addComponent(largeur1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(longueur1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EditionPanelLayout.createSequentialGroup()
                        .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditionPanelLayout.createSequentialGroup()
                                .addComponent(longueurLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(largeurLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonDeplacer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(EditionPanelLayout.createSequentialGroup()
                                .addComponent(longueurLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(largeurLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(EditionPanelLayout.createSequentialGroup()
                                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(AxeX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AxeY)
                                    .addGroup(EditionPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(EditionPanelLayout.createSequentialGroup()
                                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EditionPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EditionPanelLayout.createSequentialGroup()
                                        .addComponent(editionTailleElementSelectionne)
                                        .addGap(27, 27, 27)
                                        .addComponent(NomElementSelectionne)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditionPanelLayout.createSequentialGroup()
                                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonSupprimerElement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditionPanelLayout.createSequentialGroup()
                                        .addComponent(largeur2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(longueur2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)))
                        .addContainerGap())))
        );
        EditionPanelLayout.setVerticalGroup(
            EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(longueurLabel1)
                    .addComponent(largeurLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(largeur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(longueur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editionTailleElementSelectionne)
                    .addComponent(NomElementSelectionne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(longueurLabel2)
                    .addComponent(largeurLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(largeur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(longueur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSupprimerElement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditionPanelLayout.createSequentialGroup()
                        .addGroup(EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AxeY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AxeX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeplacer)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout oldDrawingPanelLayout = new javax.swing.GroupLayout(oldDrawingPanel);
        oldDrawingPanel.setLayout(oldDrawingPanelLayout);
        oldDrawingPanelLayout.setHorizontalGroup(
            oldDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oldDrawingPanelLayout.createSequentialGroup()
                .addComponent(EditionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 531, Short.MAX_VALUE))
        );
        oldDrawingPanelLayout.setVerticalGroup(
            oldDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oldDrawingPanelLayout.createSequentialGroup()
                .addComponent(EditionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(oldDrawingPanel, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 102));

        SaveProjectMenu.setForeground(new java.awt.Color(255, 255, 255));
        SaveProjectMenu.setText("File");

        saveProject.setText("Save Project");
        saveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProjectActionPerformed(evt);
            }
        });
        SaveProjectMenu.add(saveProject);

        LoadProjectMenu.setText("Load Project");
        SaveProjectMenu.add(LoadProjectMenu);

        exportPNG.setText("Export PNG");
        SaveProjectMenu.add(exportPNG);

        nouvellePiece.setText("Nouvelle pièce");
        nouvellePiece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouvellePieceActionPerformed(evt);
            }
        });
        SaveProjectMenu.add(nouvellePiece);
        SaveProjectMenu.add(jSeparator1);

        zoomIn.setText("Zoom in");
        zoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomInActionPerformed(evt);
            }
        });
        SaveProjectMenu.add(zoomIn);

        zoomOut.setText("Zoom out");
        SaveProjectMenu.add(zoomOut);

        jMenuBar1.add(SaveProjectMenu);

        editMenu.setForeground(new java.awt.Color(255, 255, 255));
        editMenu.setText("Edit");

        undoMenu.setText("undo");
        undoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoMenuActionPerformed(evt);
            }
        });
        editMenu.add(undoMenu);

        redoMenu.setText("redo");
        redoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoMenuActionPerformed(evt);
            }
        });
        editMenu.add(redoMenu);

        jMenuBar1.add(editMenu);

        quitMenu.setForeground(new java.awt.Color(242, 242, 242));
        quitMenu.setText("Quit");
        jMenuBar1.add(quitMenu);

        AjouterElementMenu.setForeground(new java.awt.Color(242, 242, 242));
        AjouterElementMenu.setText("Ajouter element");

        jMenu2.setText("Meuble");

        jMenu8.setText("Avec Drain");

        jMenuItem6.setText("Douche");
        jMenu8.add(jMenuItem6);

        jMenuItem8.setText("Toilette");
        jMenu8.add(jMenuItem8);

        jMenuItem9.setText("Bain");
        jMenu8.add(jMenuItem9);

        jMenuItem10.setText("Vanité");
        jMenu8.add(jMenuItem10);

        jMenu2.add(jMenu8);

        jMenu9.setText("Sans Drain");

        jMenuItem3.setText("Placard");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem3);

        jMenuItem7.setText("Armoire");
        jMenu9.add(jMenuItem7);

        jMenu2.add(jMenu9);

        AjouterElementMenu.add(jMenu2);

        jMenuItem4.setText("ElementChauffant");
        AjouterElementMenu.add(jMenuItem4);

        jMenuItem5.setText("Thermostat");
        AjouterElementMenu.add(jMenuItem5);

        jMenuBar1.add(AjouterElementMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoMenuActionPerformed
            controleur.redo();
            oldDrawingPanel.repaint();
    }//GEN-LAST:event_redoMenuActionPerformed

    private void saveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveProjectActionPerformed

    private void zoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoomInActionPerformed

    private void ModeAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeAppActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        controleur.ajouterMeubleSansDrain(100, 100, 70, 110, TypeMeubleSansDrain.PLACARD);
        oldDrawingPanel.repaint(); // pour redessiner
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //Créer une pièce depuis le menu File -> nouvelle pièce 
    //on crée une nouvelle pièce avec des valeurs par défaut
    private void nouvellePieceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouvellePieceActionPerformed
        // TODO add your handling code here:
        // Crée une pièce avec des dimensions par défaut
        controleur.creerPieceReguliere(320, 120, 400, 300);
        oldDrawingPanel.repaint();
    
        //met à jour les champs pour refléter les nouvelles valeurs
        largeur1.setText("400");
        longueur1.setText("300");
    }//GEN-LAST:event_nouvellePieceActionPerformed

    private void undoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoMenuActionPerformed
        controleur.undo();
        oldDrawingPanel.repaint();
    }//GEN-LAST:event_undoMenuActionPerformed

    private void jButtonDeplacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeplacerActionPerformed
        try {
            int nouvelX = Integer.parseInt(AxeX.getText().trim());
            int nouvelY = Integer.parseInt(AxeY.getText().trim());

            boolean ok = controleur.deplacerMeubleSelectionne(nouvelX, nouvelY);
            if (!ok) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Aucun meuble sélectionné.",
                    "Déplacement",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            oldDrawingPanel.repaint();

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Veuillez entrer des nombres valides pour X et Y.",
                "Erreur",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeplacerActionPerformed

    private void AxeXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AxeXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AxeXActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            // Récupérer les valeurs des champs
            int largeur = Integer.parseInt(largeur1.getText());
            int longueur = Integer.parseInt(longueur1.getText());

            // Récupérer l'unité sélectionnée
            String unite = (String) jComboBox4.getSelectedItem();
            /*
            // Conversion inch -> px
            if (unite.equals("inch")) {
                largeur = (int)(largeur * 2.54); // conversion approximative
                longueur = (int)(longueur * 2.54);
            }
            */
            // Créer la nouvelle pièce via le contrôleur
            controleur.creerPieceReguliere(320, 120, largeur, longueur);

            // Redessiner
            oldDrawingPanel.repaint();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erreur: Veuillez entrer des nombres valides!",
                "Erreur",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void longueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longueur2ActionPerformed

    private void largeur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largeur2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            int nouvelleLargeur = Integer.parseInt(largeur2.getText().trim());
            int nouvelleLongueur = Integer.parseInt(longueur2.getText().trim());

            boolean ok = controleur.redimensionnerMeubleSelectionne(nouvelleLargeur, nouvelleLongueur);
            if (!ok) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Aucun meuble sélectionné ou valeurs invalides.",
                    "Redimensionnement",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            oldDrawingPanel.repaint();
            afficherMeubleSelectionne();

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Veuillez entrer des nombres valides pour largeur/longueur.",
                "Erreur",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void longueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longueur1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void largeur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largeur1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // Récupérer les valeurs des champs du deuxième groupe
            int largeur = Integer.parseInt(largeur1.getText());
            int longueur = Integer.parseInt(longueur1.getText());

            // Récupérer l'unité sélectionnée
            String unite = (String) jComboBox5.getSelectedItem();
            /*
            // Conversion inch -> px si nécessaire
            if (unite.equals("inch")) {
                largeur = (int)(largeur * 2.54);
                longueur = (int)(longueur * 2.54);
            }
            */
            // Redimensionner la pièce via le contrôleur
            controleur.redimensionnerPiece(largeur, longueur);

            // Redessiner
            oldDrawingPanel.repaint();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erreur: Veuillez entrer des nombres valides!",
                "Erreur",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonSupprimerElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerElementActionPerformed
         boolean ok = controleur.supprimerMeubleSelectionne();
    if (!ok) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aucun meuble sélectionné.",
            "Suppression",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Nettoie l’UI
    NomElementSelectionne.setText("** ??? **");
    largeur2.setText("");
    longueur2.setText("");
    AxeX.setText("0");
    AxeY.setText("0");

    oldDrawingPanel.repaint();
    }//GEN-LAST:event_buttonSupprimerElementActionPerformed

     private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt){
        controleur.ajouterMeubleSansDrain(200, 100, 70, 70, TypeMeubleSansDrain.ARMOIRE);
        oldDrawingPanel.repaint();

    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       // JFrame frame = new JFrame("Grille");
        //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //frame.setSize(400, 400); // ça c la taille de ma fenêtre
        //frame.add(new DrawingPanel());
        //frame.setVisible(true); // affiche la fenêtre
          java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true); // FIX
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AjouterElementMenu;
    private javax.swing.JTextField AxeX;
    private javax.swing.JTextField AxeY;
    private javax.swing.JPanel ButtonTopPanel;
    private javax.swing.JPanel EditionPanel;
    private javax.swing.JMenuItem LoadProjectMenu;
    private javax.swing.JLabel ModeActive;
    private javax.swing.JComboBox<String> ModeApp;
    private javax.swing.JLabel NomElementSelectionne;
    private javax.swing.JMenu SaveProjectMenu;
    private javax.swing.JButton buttonSupprimerElement;
    private javax.swing.JMenu editMenu;
    private javax.swing.JLabel editionTailleElementSelectionne;
    private javax.swing.JMenuItem exportPNG;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonDeplacer;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField largeur1;
    private javax.swing.JTextField largeur2;
    private javax.swing.JLabel largeurLabel1;
    private javax.swing.JLabel largeurLabel2;
    private javax.swing.JTextField longueur1;
    private javax.swing.JTextField longueur2;
    private javax.swing.JLabel longueurLabel1;
    private javax.swing.JLabel longueurLabel2;
    private javax.swing.JMenuItem nouvellePiece;
    private javax.swing.JPanel oldDrawingPanel;
    private javax.swing.JMenu quitMenu;
    private javax.swing.JMenuItem redoMenu;
    private javax.swing.JMenuItem saveProject;
    private javax.swing.JMenuItem undoMenu;
    private javax.swing.JMenuItem zoomIn;
    private javax.swing.JMenuItem zoomOut;
    // End of variables declaration//GEN-END:variables
}


